import type { account, session, user, verification } from "./auth";
import type { systemSettings } from "./system-settings";
import type { transcript } from "./transcript";
import type { commonTableCols } from "./utils";

export type DBAutoGeneratedValues = keyof typeof commonTableCols;

export type User = typeof user.$inferSelect;
export type Session = typeof session.$inferSelect;
export type Account = typeof account.$inferSelect;
export type Verification = typeof verification.$inferSelect;

export type SystemSettings = typeof systemSettings.$inferSelect;
export type Transcript = typeof transcript.$inferSelect;
